### ISSUE TITLE
Double index 1 course code problem

### ISSUE THREAD

**Issue by hanstananda** [TechBotGit/bot#22]
Input any course code, press available indexes more than once, and voila! multiple input! 
The database seems to be not updated alongside with it tho.

**Comment by hanstananda** [comment]
![image](https://user-images.githubusercontent.com/21126223/31086288-091d5b58-a7cc-11e7-964d-dcc4e1fa322e.png)
![image](https://user-images.githubusercontent.com/21126223/31086308-1694c91a-a7cc-11e7-8c54-fbddd1bee5b7.png)

**Comment by hanstananda** [comment]
![image](https://user-images.githubusercontent.com/21126223/31086372-42a73be6-a7cc-11e7-9861-d216fc7b763a.png)
Database only records the first one(seems)

**Comment by TechBotGit** [comment]
wakakkaka... how do you handle this?? masak pake if? ada ndak yang built in nya telegram? @hanstananda

**Comment by hanstananda** [comment]
i dont know kalau built in nya telegram sih coba cari aja apa dia punya parameter once use lolol

**Comment by TechBotGit** [comment]
# Okay Noted

**Comment by hanstananda** [comment]
Case fixed.
