### ISSUE TITLE
/removeindex from the beginning

### ISSUE THREAD

**Issue by TechBotGit** [TechBotGit/bot#24]
Error, because `BotCommandObject` has not been defined (either locally or globally)

<img width="743" alt="screen shot 2017-10-02 at 23 43 41" src="https://user-images.githubusercontent.com/31700016/31088737-efe0e646-a7cb-11e7-9cef-1fbbd86aaca8.png">

**Comment by hanstananda** [comment]
Solved
![image](https://user-images.githubusercontent.com/21126223/31088846-a2d3a4fc-a7d4-11e7-803e-470a8d041aeb.png)
